import { useMemo, useState } from 'react'
import { platforms } from '../../data/dashboard.js'
import { REFERENCE_TODAY, WEEKDAY_LABELS, addDays, formatTime, isSameDay, startOfWeek, toDate } from '../../lib/dates.js'
import { useDashboard } from '../../state/DashboardContext.jsx'
import { CalendarIcon, ChartIcon, ChevronLeftIcon, ChevronRightIcon, InstagramIcon, LinkedInIcon, PlusIcon, YouTubeIcon } from '../icons.jsx'
import SectionHeader, { card, primaryButton } from './SectionHeader.jsx'

const colors = { instagram:'rose', youtube:'red', linkedin:'blue' }
const icons = { instagram:InstagramIcon, youtube:YouTubeIcon, linkedin:LinkedInIcon }
const stages = [{id:'idea',label:'Ideas',hint:'Por desarrollar'},{id:'production',label:'En producción',hint:'Diseño y edición'},{id:'review',label:'En revisión',hint:'Pendiente de aprobación'},{id:'scheduled',label:'Programado',hint:'Listo para publicar'}]

export default function CalendarMonth({ onSchedule }) {
  const { posts } = useDashboard()
  const [offset,setOffset] = useState(0)
  const [view,setView] = useState('board')
  const [filter,setFilter] = useState('all')
  const month = new Date(REFERENCE_TODAY.getFullYear(),REFERENCE_TODAY.getMonth()+offset,1)
  const visiblePosts = filter==='all' ? posts : posts.filter(p=>p.platform===filter)
  const days = useMemo(()=>{const first=startOfWeek(month);return Array.from({length:42},(_,i)=>{const date=addDays(first,i);return {date,inMonth:date.getMonth()===month.getMonth(),isToday:isSameDay(date,REFERENCE_TODAY),posts:visiblePosts.filter(p=>isSameDay(toDate(p.at),date))}})},[month,visiblePosts])
  const monthLabel=month.toLocaleDateString('es-ES',{month:'long',year:'numeric'})
  const boardPosts=[...visiblePosts,{id:'idea-1',platform:'linkedin',title:'7 aprendizajes al automatizar contenido',format:'Carrusel',stage:'idea'},{id:'prod-1',platform:'youtube',title:'Cómo crear 30 piezas desde un vídeo',format:'Vídeo largo',stage:'production'},{id:'review-1',platform:'instagram',title:'Errores que frenan tu alcance',format:'Reel',stage:'review'}]
  return <>
    <SectionHeader title="Planificador de contenido" subtitle="Planea, produce y publica sin salir del tablero"><button type="button" onClick={()=>onSchedule({})} className={primaryButton}><PlusIcon className="w-4 h-4"/> Crear contenido</button></SectionHeader>
    <div className="flex flex-wrap items-center justify-between gap-3"><div className="segmented-control"><button onClick={()=>setView('board')} className={view==='board'?'active':''}><ChartIcon className="w-4 h-4"/>Tablero</button><button onClick={()=>setView('calendar')} className={view==='calendar'?'active':''}><CalendarIcon className="w-4 h-4"/>Calendario</button><button onClick={()=>setView('canvas')} className={view==='canvas'?'active':''}><span className="text-base">✦</span>Canvas</button></div><div className="flex items-center gap-2"><select className="premium-select" value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Filtrar red"><option value="all">Todas las redes</option>{Object.values(platforms).map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select><button className="premium-button secondary">⚡ Automatizar</button></div></div>
    {view==='board'&&<div className="kanban-grid">{stages.map(stage=>{const items=boardPosts.filter(p=>(p.stage||'scheduled')===stage.id);return <section key={stage.id} className="kanban-column"><header><div><h3>{stage.label}</h3><p>{stage.hint}</p></div><span>{items.length}</span></header><div className="space-y-3">{items.map(post=>{const Icon=icons[post.platform]||InstagramIcon;return <article key={post.id} className="kanban-card"><div className="flex items-center justify-between"><span className={`platform-token ${colors[post.platform]}`}><Icon className="w-3.5 h-3.5"/>{platforms[post.platform]?.label}</span><button aria-label={`Opciones de ${post.title}`} className="icon-button">•••</button></div><h4>{post.title}</h4><p>{post.format} · {post.at?`${new Date(post.at).getDate()} Sep, ${formatTime(post.at)}`:'Sin fecha'}</p><div className="mt-4 flex items-center justify-between"><div className="flex -space-x-1"><span className="avatar-dot">AG</span><span className="avatar-dot alt">+</span></div><button onClick={()=>onSchedule(post)} className="quick-action">Abrir →</button></div></article>})}<button onClick={()=>onSchedule({})} className="add-card"><PlusIcon className="w-4 h-4"/> Añadir contenido</button></div></section>})}</div>}
    {view==='calendar'&&<div className={`${card} premium-card p-5`}><div className="flex items-center justify-between mb-5"><button onClick={()=>setOffset(offset-1)} className="icon-button"><ChevronLeftIcon className="w-4 h-4"/></button><button onClick={()=>setOffset(0)} className="font-bold text-sm capitalize">{monthLabel}</button><button onClick={()=>setOffset(offset+1)} className="icon-button"><ChevronRightIcon className="w-4 h-4"/></button></div><div className="calendar-grid">{WEEKDAY_LABELS.map(l=><div key={l} className="weekday">{l}</div>)}{days.map(({date,inMonth,isToday,posts:items})=><div key={date.toISOString()} className={`calendar-day ${!inMonth?'muted':''} ${isToday?'today':''}`}><div className="flex justify-between"><span>{date.getDate()}</span><button onClick={()=>onSchedule({date:date.toISOString()})}>+</button></div>{items.map(p=><button key={p.id} onClick={()=>onSchedule(p)} className={`calendar-event ${colors[p.platform]}`}>{formatTime(p.at)} · {p.title}</button>)}</div>)}</div></div>}
    {view==='canvas'&&<div className="canvas-board"><div className="canvas-grid-bg"/><div className="canvas-note note-one"><span>01 · OBJETIVO</span><h3>Convertir atención en conversaciones</h3><p>Una idea central para toda la campaña del mes.</p></div><div className="canvas-line line-one"/><div className="canvas-note note-two"><span>02 · PILARES</span><h3>Autoridad · Conexión · Tráfico</h3><p>Alternar el enfoque sin perder coherencia.</p></div><div className="canvas-line line-two"/><div className="canvas-note note-three"><span>03 · DISTRIBUCIÓN</span><h3>1 idea → 7 contenidos</h3><p>YouTube, carrusel, post y secuencia de historias.</p></div><button onClick={()=>onSchedule({})} className="canvas-add"><PlusIcon className="w-4 h-4"/> Nueva idea</button></div>}
  </>
}
